# Generated by Django 3.2.3 on 2021-06-11 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_auto_20210611_1055'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='published',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='author',
            name='image',
            field=models.ImageField(default=1, upload_to='images/author/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default=1, upload_to='images/post/'),
            preserve_default=False,
        ),
    ]
