# Generated by Django 3.2.3 on 2021-06-11 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_auto_20210611_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
